From here https://docs.scipy.org/doc/numpy/reference/index.html

In [2]:
import numpy as np
print (np.__version__)

1.15.4


## The N-dimensional array (ndarray)

https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [13]:
#A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [14]:
print(f'type(x): {type(x)}')
print(f'x.shape: {x.shape}')
print(f'x.dtype: {x.dtype}')

type(x): <class 'numpy.ndarray'>
x.shape: (2, 3)
x.dtype: int32


In [15]:
# The element of x in the *second* row, *third* column, namely, 6.
print(f'x[1, 2]: {x[1, 2]}')

x[1, 2]: 6


In [16]:
y = x[:,1] # row:all, column: *second*.
print(f'y: {y}')
print(f'type(y): {type(y)}')
print(f'y.shape: {y.shape}')
print()

y[0] = 9 # this also changes the corresponding element in x
print(f'y: {y}')
print()

print(f'x: {x}')

y: [2 5]
type(y): <class 'numpy.ndarray'>
y.shape: (2,)

y: [9 5]

x: [[1 9 3]
 [4 5 6]]


### Array attributes

#### Memory layout

In [32]:
print(f'{x}')
print(f'****************')

print(f'ndarray.flags	Information about the memory layout of the array.')
print(f'{x.flags}')
print(f'ndarray.shape	Tuple of array dimensions.')
print(f'{x.shape}')
print(f'ndarray.strides	Tuple of bytes to step in each dimension when traversing an array.')
print(f'{x.strides}')
print(f'ndarray.ndim	Number of array dimensions.')
print(f'{x.ndim}')
print(f'ndarray.data	Python buffer object pointing to the start of the array’s data.')
print(f'{x.data}')
print(f'ndarray.size	Number of elements in the array.')
print(f'{x.size}')
print(f'ndarray.itemsize	Length of one array element in bytes.')
print(f'{x.itemsize}')         
print(f'ndarray.nbytes	Total bytes consumed by the elements of the array.')
print(f'{x.nbytes}')
print(f'ndarray.base	Base object if memory is from some other object.')
print(f'{x.base}')

[[1 9 3]
 [4 5 6]]
****************
ndarray.flags	Information about the memory layout of the array.
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
ndarray.shape	Tuple of array dimensions.
(2, 3)
ndarray.strides	Tuple of bytes to step in each dimension when traversing an array.
(12, 4)
ndarray.ndim	Number of array dimensions.
2
ndarray.data	Python buffer object pointing to the start of the array’s data.
ndarray.size	Number of elements in the array.
6
ndarray.itemsize	Length of one array element in bytes.
4
ndarray.nbytes	Total bytes consumed by the elements of the array.
24
ndarray.base	Base object if memory is from some other object.
None


#### Data type

In [33]:
print(f'x.dtype: {x.dtype}')

x.dtype: int32


#### Other attributes

In [34]:

print(f'{x}')
print(f'****************')

print(f'ndarray.T	The transposed array.')
print(f'{x.T}')
print(f'ndarray.real	The real part of the array.')
print(f'{x.real}')
print(f'ndarray.imag	The imaginary part of the array.')
print(f'{x.imag}')
print(f'ndarray.flat	A 1-D iterator over the array.')
print(f'{x.flat}')
print(f'ndarray.ctypes	An object to simplify the interaction of the array with the ctypes module.')
print(f'{x.flat}')

[[1 9 3]
 [4 5 6]]
****************
ndarray.T	The transposed array.
[[1 4]
 [9 5]
 [3 6]]
ndarray.real	The real part of the array.
[[1 9 3]
 [4 5 6]]
ndarray.imag	The imaginary part of the array.
[[0 0 0]
 [0 0 0]]
ndarray.flat	A 1-D iterator over the array.
ndarray.ctypes	An object to simplify the interaction of the array with the ctypes module.


### Array methods

#### Array conversion

In [74]:
#A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(f'{x}')
print(f'****************\n')

print(f'ndarray.item(*args)	Copy an element of an array to a standard Python scalar and return it.')
print(f'{x.item(1)}\n')

print(f'ndarray.tolist()	Return the array as an a.ndim-levels deep nested list of Python scalars.')
print(f'{x.tolist()}\n')

print(f'ndarray.itemset(*args)	Insert scalar into an array (scalar is cast to array’s dtype, if possible)')
print(f'{x.itemset(2,555)}')
print(f'{x}\n')

print(f'ndarray.tostring([order])	Construct Python bytes containing the raw data bytes in the array.')
print(f'{x.tostring()}\n')

print(f'ndarray.tobytes([order])	Construct Python bytes containing the raw data bytes in the array.')
print(f'{x.tobytes()}')

print(f'ndarray.tofile(fid[, sep, format])	Write array to a file as text or binary (default).')
print(f'ndarray.dump(file)	Dump a pickle of the array to the specified file.')
print(f'ndarray.dumps()	Returns the pickle of the array as a string.\n')


print(f'ndarray.astype(dtype[, order, casting, …])	Copy of the array, cast to a specified type.')
print(f'{x.astype(float)}\n')

print(f'ndarray.byteswap([inplace])	Swap the bytes of the array elements')
print(f'{x.byteswap()}\n')

print(f'ndarray.copy([order])	Return a copy of the array.')
print(f'{x.copy()}\n')

print(f'ndarray.view([dtype, type])	New view of array with the same data.')
print(f"{x.view(dtype=np.int32,type=np.ndarray)}\n")

print(f'ndarray.getfield(dtype[, offset])	Returns a field of the given array as a certain type.')
print(f'{x.getfield(np.float64)}\n')

print(f'ndarray.setflags([write, align, uic])	Set array flags WRITEABLE, ALIGNED, (WRITEBACKIFCOPY and UPDATEIFCOPY), respectively.')
print(f'{x.setflags(write=True)}\n')
x.itemset(2,222)

print(f'ndarray.fill(value)	Fill the array with a scalar value.')
x.fill(111)
print(f'{x}')

[[1 2 3]
 [4 5 6]]
****************

ndarray.item(*args)	Copy an element of an array to a standard Python scalar and return it.
2

ndarray.tolist()	Return the array as an a.ndim-levels deep nested list of Python scalars.
[[1, 2, 3], [4, 5, 6]]

ndarray.itemset(*args)	Insert scalar into an array (scalar is cast to array’s dtype, if possible)
None
[[  1   2 555]
 [  4   5   6]]

ndarray.tostring([order])	Construct Python bytes containing the raw data bytes in the array.
b'\x01\x00\x00\x00\x02\x00\x00\x00+\x02\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00'

ndarray.tobytes([order])	Construct Python bytes containing the raw data bytes in the array.
b'\x01\x00\x00\x00\x02\x00\x00\x00+\x02\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00'
ndarray.tofile(fid[, sep, format])	Write array to a file as text or binary (default).
ndarray.dump(file)	Dump a pickle of the array to the specified file.
ndarray.dumps()	Returns the pickle of the array as a string.

ndarray.astype(dtype[, 

#### Shape manipulation

In [106]:
#For reshape, resize, and transpose, the single tuple argument may be replaced with n integers which will be interpreted as an n-tuple.

#A 2-dimensional array of size 2 x 3, composed of 4-byte integer elements:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(f'{x}')
print(f'****************\n')

print(f'ndarray.reshape(shape[, order])	Returns an array containing the same data with a new shape.')
print(f'{x.reshape(6)}\n')
print(f'{x.reshape(3,2)}\n')
      
print(f'ndarray.resize(new_shape[, refcheck])	Change shape and size of array in-place.')
print(f'{x.resize(3,2)}')
print(f'{x}\n')
      
print(f'ndarray.transpose()	Returns a view of the array with axes transposed.')
print(f'{x.transpose()}\n')
      
print(f'ndarray.swapaxes(axis1, axis2)	Return a view of the array with axis1 and axis2 interchanged.')
print(f'{x}')
print(f'{x.swapaxes(1,0)}\n')
      
print(f'ndarray.flatten([order])	Return a copy of the array collapsed into one dimension.')
print(f'{x.flatten()}')
print(f'{type(x.flatten())}\n')
      
print(f'ndarray.ravel([order])	Return a flattened array.')
print(f'{x.ravel()}')
print(f'{type(x.ravel())}\n')
      
print(f'ndarray.squeeze([axis])	Remove single-dimensional entries from the shape of a.')
print(f'{x[2:,]}')
print(f'{x[2:,].squeeze()}\n')

[[1 2 3]
 [4 5 6]]
****************

ndarray.reshape(shape[, order])	Returns an array containing the same data with a new shape.
[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

ndarray.resize(new_shape[, refcheck])	Change shape and size of array in-place.
None
[[1 2]
 [3 4]
 [5 6]]

ndarray.transpose()	Returns a view of the array with axes transposed.
[[1 3 5]
 [2 4 6]]

ndarray.swapaxes(axis1, axis2)	Return a view of the array with axis1 and axis2 interchanged.
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]

ndarray.flatten([order])	Return a copy of the array collapsed into one dimension.
[1 2 3 4 5 6]
<class 'numpy.ndarray'>

ndarray.ravel([order])	Return a flattened array.
[1 2 3 4 5 6]
<class 'numpy.ndarray'>

ndarray.squeeze([axis])	Remove single-dimensional entries from the shape of a.
[[5 6]]
[5 6]

